name: Get daily availability

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:  # manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.2/install.sh | sh
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Get new availability data
        run: |
          uv run scripts/get_daily.py --out data/daily.csv --start 2024-09-10 --end 2024-09-28
      - name: Commit and push to availability branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'leonlan@users.noreply.github.com'
          git fetch origin
          git add data/daily.csv
          git commit -m "Update daily availability $(date +%Y-%m-%d)"
